import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  weight: ['500', '400', '700'],
})

export const metadata = {
  title: 'Carrinho de Compras',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutrals-bg leading-6`}>
        {children}
      </body>
    </html>
  )
}
